logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: WARN
    resolver: DEBUG

server:
  server-header: no
  session:
    timeout: "28800"
    cookie:
      secure: false

security:
  api_users_config_path: classpath:/id-resolver-api-users.yml

spring:
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/id_resolver?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
