---
env_name: lab

id_resolver_gui_version: 0.0.1-SNAPSHOT
id_resolver_server_version: 0.0.1-SNAPSHOT

id_resolver_mysql_url: "jdbc:mysql://localhost/id_resolver"

id_resolver:
  apiUsers:
    - {
        name: "user",
        password: "{{ id_resolver_user_secret }}",
        organisation: "example.org",
        scopes: ["READ", "WRITE"]
      }
    - {
        name: "groningen",
        password: "{{ id_resolver_groningen_secret }}",
        organisation: "example.org",
        scopes: ["READ", "WRITE"]
      }
    - {
        name: "herman",
        password: "{{ id_resolver_herman_secret }}",
        organisation: "herman",
        scopes: ["READ", "WRITE"]
      }
    - {
        name: "clifford",
        password: "{{ id_resolver_clifford_secret }}",
        organisation: "surfmarket",
        scopes: ["READ", "WRITE"]
      }
    - {
        name: "nick",
        password: "{{ id_resolver_nick_secret }}",
        organisation: "tue",
        scopes: ["READ", "WRITE"]
      }
    - {
        name: "peter",
        password: "{{ id_resolver_peter_secret }}",
        organisation: "lu",
        scopes: ["READ", "WRITE"]
      }
    - {
        name: "ivo",
        password: "{{ id_resolver_ivo_secret }}",
        organisation: "um",
        scopes: ["READ", "WRITE"]
      }
    - {
        name: "david",
        password: "{{ id_resolver_david_secret }}",
        organisation: "uu",
        scopes: ["READ", "WRITE"]
      }

apache_listen_port: 443
apache_create_vhosts: true
apache_vhosts_filename: "id_resolver.conf"
apache_vhosts_template: "templates/id_resolver.conf.j2"
apache_remove_default_vhost: true
apache_ignore_missing_ssl_certificate: false
apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - rewrite.load
  - mime.load
  - proxy.load
  - proxy_http.load

apache_app_listen_address:
  id_resolver: 145.101.124.16
loadbalancing:
  id_resolver:
    port: 443
tls:
  cert_file: /etc/letsencrypt/live/idresolver.lab.surf.nl/fullchain.pem
  cert_private_file: /etc/letsencrypt/live/idresolver.lab.surf.nl/privkey.pem
  cert_chain_file: /etc/letsencrypt/live/idresolver.lab.surf.nl/chain.pem

