---
env_name: lab

id_resolver_gui_version: 0.0.1-SNAPSHOT
id_resolver_server_version: 0.0.1-SNAPSHOT

id_resolver_mysql_url: "jdbc:mysql://localhost/id_resolver"

id_resolver:
  apiUsers:
    - {
        name: "user",
        password: "{{ id_resolver_user_secret }}",
        scopes: ["READ", "WRITE"]
      }
