---
- hosts: all
  gather_facts: no
  tasks:
  - name: Read vars from secrets file
    include_vars: "{{ secrets_file }}"
    tags:
      - always

- hosts: id-resolver
  become: true
  gather_facts: yes
  vars_files:
      - group_vars/id-resolver-lab.yml
  roles:
#    - role: geerlingguy.java
#      when: "ansible_os_family == 'Debian'"
#      java_packages:
#        - openjdk-8-jdk
    - initial
    - { role: java, tags: java }
    - { role: mysql, tags: mysql }
    - { role: geerlingguy.apache, tags: apache }
    - { role: id-resolver-gui, tags: id-resolver-gui }
    - { role: id-resolver-server, tags: id-resolver-server }
